
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "Test__BaseScreen":RBSFM_getFunctions_Test__BaseScreen 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_Test__BaseScreen()
  return {
    "BaseScreen__createExitDialog_returns_Dialog_node":BaseScreen__createExitDialog_returns_Dialog_node 
  } 

end function

function RBSFM_getFilenames()
  return [
    "Test__BaseScreen", 
  ] 
end function




    function RBSFM_getRuntimeConfig()
        return {
          "failFast": true
          "logLevel": 2
          "showOnlyFailures": true
          "printLcov": false
          "rooibosPreprocessorVersion": "1.4.0"
          "port": Invalid
          }
    end function
    

    function RBSFM_getPreprocessorVersion()
        return "1.4.0"
    end function
    

    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "BaseScreen"
      filePath: "source/tests/specs/Test__BaseScreen.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "BaseScreen__createExitDialog_returns_Dialog_node"
          isIgnored: false
          isParamTest: false
          name: "returns a Dialog node"
          lineNumber: 7
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":10}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "Test__BaseScreen"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: ""
        afterEachFunctionName: ""
        isSolo: false
        isLegacy: false
        isIgnored: false
        hasSoloTests: false
        name: "createExitDialog"
      }]
      setupFunctionName: ""
      tearDownFunctionName: ""
      isNodeTest: true
      isLegacy: false
      nodeTestFileName: "Test__BaseScreen"
      beforeEachFunctionName: ""
      afterEachFunctionName: ""
    },

      ]
    end function


    function RBSFM_getIgnoredTestInfo()
        return {
          "count": 0
          "items":[
        
      ]}
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    